# Generated by Django 4.0.3 on 2022-12-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airtelplans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('validity', models.CharField(max_length=10)),
                ('sms', models.IntegerField()),
                ('data', models.CharField(max_length=10)),
                ('postpaid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Jioplans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('validity', models.CharField(max_length=10)),
                ('sms', models.IntegerField()),
                ('data', models.CharField(max_length=10)),
                ('postpaid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VIplans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('validity', models.CharField(max_length=10)),
                ('sms', models.IntegerField()),
                ('data', models.CharField(max_length=10)),
                ('postpaid', models.BooleanField()),
            ],
        ),
    ]
