# Generated by Django 4.0.3 on 2022-12-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtelplans',
            name='data',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jioplans',
            name='data',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='viplans',
            name='data',
            field=models.CharField(max_length=20),
        ),
    ]
