# Generated by Django 4.0.3 on 2022-12-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0002_alter_airtelplans_data_alter_jioplans_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobilenumber', models.CharField(max_length=20)),
                ('Airtelplans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechargeapp.airtelplans')),
                ('Jioplans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechargeapp.jioplans')),
                ('VIplans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechargeapp.viplans')),
            ],
        ),
    ]
