# Generated by Django 4.0.3 on 2022-12-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0003_recharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recharge',
            name='Mobilenumber',
        ),
    ]
